### ISSUE TITLE
Updates stalled

### ISSUE THREAD

**Issue by Danik1601** [flathub/org.syphon.Syphon#4]
The latest version is currently 0.2.14 ([releases](https://github.com/syphon-org/syphon/releases)), but only 0.2.13 is available on Flathub. Please fix

**Comment by 0x1a8510f2** [comment]
Hmm, looks like the flathubbot PR didn't come through. Will update manually.

**Comment by 0x1a8510f2** [comment]
Turns out the build artefact names have changed so the bot didn't pick up the new release. Should be fixed now and the new release should be live shortly! :D
